### ISSUE TITLE
Router 4 HSRP already 150 and preempt

### ISSUE THREAD

**Issue by anyone2** [arharris2/NetworkingInterviewLab#1]
I'm playing around with this, converting it to CML, after checking out multiple things on your blog, which is awesome btw.

Task #4 is "Configure Router4 to be preferred as the HSRP active forwarder. Verify functionality with the “show standby” command"

The HSRP priority of Router4 is 150 and preempt is enabled.  Router3 is 100 w/o Preempt disabled. So if I were doing this interview lab, I would skip this task as completed, since Router4 is already the HSRP active forwarder.

With your skill level, I kinda feel I'm overlooking something but I've lab'd it twice, and I'm not seeing it.

**Comment by arharris2** [comment]
Good call. You are correct. It appears that I must have accidentally uploaded the wrong file. I was going back and forth a lot when I did this and working through different issues to make sure the objectives made sense. I've updated the router4 config to lower the priority and remove the preemption.
